package ru.e6atb.chat

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.security.MessageDigest

/** Small on-device cache. It deliberately stores only serialized public chat state. */
internal object ChatCache {
    @JvmStatic @Synchronized fun saveChats(context: Context?, server: String?, login: String?, chats: List<MST5.Chat>?) { try { write(context, key(server, login, "chats"), JSONArray().also { array -> chats?.forEach { array.put(chatToJson(it)) } }.toString()) } catch (_: Exception) { } }
    @JvmStatic @Synchronized fun loadChats(context: Context?, server: String?, login: String?): List<MST5.Chat> = try { JSONArray(read(context, key(server, login, "chats"))).let { array -> ArrayList<MST5.Chat>().also { out -> for (index in 0 until array.length()) out += chat(array.getJSONObject(index)) } } } catch (_: Exception) { ArrayList() }
    @JvmStatic @Synchronized fun saveHistory(context: Context?, server: String?, login: String?, peer: String?, messages: List<MST5.Message>?) { try { write(context, key(server, login, "history\n$peer"), JSONArray().also { array -> messages?.forEach { array.put(messageToJson(it)) } }.toString()); if (peer?.startsWith("comments:") == true) rememberCommentPeer(context, server, login, peer) } catch (_: Exception) { } }
    @JvmStatic @Synchronized fun loadHistory(context: Context?, server: String?, login: String?, peer: String?): List<MST5.Message> = try { JSONArray(read(context, key(server, login, "history\n$peer"))).let { array -> ArrayList<MST5.Message>().also { out -> for (index in 0 until array.length()) out += message(array.getJSONObject(index)) } } } catch (_: Exception) { ArrayList() }
    @JvmStatic @Synchronized fun appendMessage(context: Context?, server: String?, login: String?, peer: String?, message: MST5.Message?) { if (message == null) return; val history = ArrayList(loadHistory(context, server, login, peer)); val index = history.indexOfFirst { it.id == message.id }; if (index >= 0) { if (message.reactionVersion < history[index].reactionVersion) return; history[index] = message } else { history += message; while (history.size > 200) history.removeAt(0) }; saveHistory(context, server, login, peer, history); if (peer?.startsWith("comments:") != true) upsertChat(context, server, login, peer, message) }
    @JvmStatic @Synchronized fun deleteMessage(context: Context?, server: String?, login: String?, peer: String?, messageId: Long) { val history = ArrayList(loadHistory(context, server, login, peer)); if (!history.removeIf { it.id == messageId }) return; saveHistory(context, server, login, peer, history); val chats = ArrayList(loadChats(context, server, login)); val index = chats.indexOfFirst { peerKey(it.peer) == peer }; if (index >= 0) { val banned = chats[index].banned; chats.removeAt(index); history.lastOrNull()?.let { last -> chats.add(index, MST5.Chat(last.chatId, messagePeerUser(last, login), last, banned)) } }; saveChats(context, server, login, chats) }
    @JvmStatic @Synchronized fun deleteChat(context: Context?, server: String?, login: String?, peer: String?) { try { write(context, key(server, login, "history\n$peer"), "[]") } catch (_: Exception) { }; saveChats(context, server, login, loadChats(context, server, login).filter { peerKey(it.peer) != peer }) }
    @JvmStatic @Synchronized fun deleteCommentThreads(context: Context?, server: String?, login: String?, channel: String?) { try { val indexKey = key(server, login, "comment_threads"); val raw = JSONArray(read(context, indexKey)); val kept = JSONArray(); val prefix = "comments:$channel:"; for (index in 0 until raw.length()) { val peer = raw.optString(index); if (peer.startsWith(prefix)) write(context, key(server, login, "history\n$peer"), "[]") else if (peer.isNotEmpty()) kept.put(peer) }; write(context, indexKey, kept.toString()) } catch (_: Exception) { } }
    private fun rememberCommentPeer(context: Context?, server: String?, login: String?, peer: String) { val indexKey = key(server, login, "comment_threads"); val raw = try { JSONArray(read(context, indexKey)) } catch (_: Exception) { JSONArray() }; if ((0 until raw.length()).none { raw.optString(it) == peer }) { raw.put(peer); write(context, indexKey, raw.toString()) } }
    private fun upsertChat(context: Context?, server: String?, login: String?, peer: String?, message: MST5.Message) { val chats = ArrayList(loadChats(context, server, login)); var banned = false; chats.indexOfFirst { peerKey(it.peer) == peer }.takeIf { it >= 0 }?.let { index -> banned = chats[index].banned; chats.removeAt(index) }; chats.add(0, MST5.Chat(message.chatId, messagePeerUser(message, login), message, banned)); saveChats(context, server, login, chats) }
    private fun messagePeerUser(message: MST5.Message?, login: String?): MST5.User { if (message == null) return MST5.User("", "", "", "", false, false, 0); if (!message.to.roomKind.isNullOrEmpty()) return message.to; return if (message.from.login == login) message.to else message.from }
    private fun peerKey(user: MST5.User?): String = user?.login?.takeIf { it.isNotEmpty() } ?: user?.id.orEmpty()
    private fun chatToJson(chat: MST5.Chat): JSONObject = JSONObject().apply { put("id", chat.id); put("peer", userToJson(chat.peer)); chat.last?.let { put("last", messageToJson(it)) }; put("banned", chat.banned); put("banned_by_me", chat.bannedByMe); put("banned_me", chat.bannedMe) }
    private fun messageToJson(message: MST5.Message): JSONObject = JSONObject().apply { put("id", message.id); put("chat_id", message.chatId); put("from", userToJson(message.from)); put("to", userToJson(message.to)); put("text", message.text); put("date", message.date); put("read_at", message.readAt); put("encrypted", message.encrypted); put("system", message.system); put("client_message_id", message.clientMessageId); put("edited_at", message.editedAt); put("delivery_state", message.deliveryState); if (message.reactionVersion > 0) put("reaction_version", message.reactionVersion); if (message.commentPostId > 0) put("comment_post_id", message.commentPostId); if (message.commentsCount > 0) put("comments_count", message.commentsCount); if (message.replyToMessageId > 0) put("reply_to_message_id", message.replyToMessageId); if (!message.data.isNullOrEmpty()) put("data", JSONObject(message.data)); put("media", JSONArray().also { list -> message.media?.forEach { file -> list.put(JSONObject().apply { put("id", file.id); put("name", file.name); put("mime", file.mime); put("size", file.size) }) } }); if (!message.reactions.isNullOrEmpty()) put("reactions", JSONArray().also { list -> message.reactions.forEach { reaction -> list.put(JSONObject().apply { put("emoji", reaction.emoji); put("count", reaction.count); put("mine", reaction.mine) }) } }); message.paidReaction?.takeIf { it.amount > 0 }?.let { paid -> put("paid_reaction", JSONObject().apply { put("amount", paid.amount); put("mine_amount", paid.mineAmount) }) }; if (!message.buttons.isNullOrEmpty()) put("buttons", JSONArray().also { list -> message.buttons.forEach { button -> list.put(JSONObject().apply { put("text", button.text); put("row", button.row); if (!button.url.isNullOrEmpty()) put("url", button.url); if (!button.callback.isNullOrEmpty()) put("callback", button.callback); if (button.payDsr > 0) put("pay_dsr", button.payDsr); if (button.swipeConfirm) put("confirm", "swipe") }) } }) }
    private fun userToJson(user: MST5.User?): JSONObject = JSONObject().apply { val value = user ?: MST5.User("", "", "", "", false, false, 0); put("id", value.id); if (!value.email.isNullOrEmpty()) put("email", value.email); put("username", value.login); if (!value.nick.isNullOrEmpty()) put("name", value.nick); if (!value.description.isNullOrEmpty()) put("description", value.description); put("verified", value.verified); put("bot", value.bot); if (value.createdAt > 0) put("created_at", value.createdAt); if (!value.roomKind.isNullOrEmpty()) { put("room_kind", value.roomKind); put("owner_id", value.ownerId); put("members", value.memberCount); put("admins", value.adminCount); put("can_manage", value.canManage); put("comments_enabled", value.commentsEnabled); put("member_users", JSONArray().also { members -> value.memberUsers.forEach { members.put(userToJson(it)) } }) } }
    private fun chat(raw: JSONObject): MST5.Chat = MST5.Chat(raw.optString("id"), user(raw.optJSONObject("peer")), raw.optJSONObject("last")?.let(::message), raw.optBoolean("banned"), raw.optBoolean("banned_by_me", raw.optBoolean("banned")), raw.optBoolean("banned_me", false))
    private fun message(raw: JSONObject): MST5.Message { val media = ArrayList<MST5.FileInfo>(); raw.optJSONArray("media")?.let { list -> for (index in 0 until list.length()) list.optJSONObject(index)?.takeIf { it.optString("id").isNotEmpty() }?.let { media += MST5.FileInfo(it.optString("id"), it.optString("name"), it.optString("mime"), it.optLong("size")) } }; return MST5.Message(raw.optLong("id"), raw.optString("chat_id"), user(raw.optJSONObject("from")), user(raw.optJSONObject("to")), raw.optString("text"), raw.optLong("date"), raw.optLong("read_at"), media, buttons(raw.optJSONArray("buttons")), raw.optBoolean("encrypted"), raw.optBoolean("system"), raw.optJSONObject("data")?.toString().orEmpty(), raw.optString("client_message_id"), raw.optLong("edited_at"), raw.optString("delivery_state", "sent"), "", reactions(raw.optJSONArray("reactions")), paidReaction(raw.optJSONObject("paid_reaction")), raw.optLong("reaction_version"), raw.optLong("comment_post_id"), raw.optInt("comments_count"), raw.optLong("reply_to_message_id")) }
    private fun reactions(raw: JSONArray?): ArrayList<MST5.Reaction> = ArrayList<MST5.Reaction>().also { out -> raw?.let { list -> for (index in 0 until list.length()) list.optJSONObject(index)?.let { item -> item.optString("emoji").takeIf { it.isNotEmpty() && item.optLong("count") > 0 }?.let { out += MST5.Reaction(it, item.optLong("count"), item.optBoolean("mine")) } } } }
    private fun paidReaction(raw: JSONObject?): MST5.PaidReaction? = raw?.takeIf { it.optLong("amount") > 0 }?.let { MST5.PaidReaction(it.optLong("amount"), it.optLong("mine_amount")) }
    private fun buttons(raw: JSONArray?): ArrayList<MST5.Button> = ArrayList<MST5.Button>().also { out -> raw?.let { list -> for (index in 0 until list.length()) { val row = list.optJSONArray(index); if (row != null) for (itemIndex in 0 until row.length()) addButton(out, row.optJSONObject(itemIndex), index) else addButton(out, list.optJSONObject(index), list.optJSONObject(index)?.optInt("row", index) ?: index) } } }
    private fun addButton(out: ArrayList<MST5.Button>, item: JSONObject?, row: Int) { item ?: return; out += MST5.Button(item.optString("text"), item.optString("url"), item.optString("callback"), item.optLong("pay_dsr"), row.coerceAtLeast(0), item.optString("confirm") == "swipe" || item.optBoolean("swipe_confirm")) }
    private fun user(raw: JSONObject?): MST5.User { if (raw == null) return MST5.User("", "", "", "", false, false, 0); val members = ArrayList<MST5.User>(); raw.optJSONArray("member_users")?.let { list -> for (index in 0 until list.length()) list.optJSONObject(index)?.let { members += user(it) } }; return MST5.User(raw.optString("id"), raw.optString("email"), raw.optString("username", raw.optString("login")), raw.optString("name", raw.optString("nick", raw.optString("title"))), raw.optBoolean("verified"), raw.optBoolean("bot"), raw.optLong("created_at"), "everyone", "everyone", "everyone", raw.optString("room_kind", raw.optString("kind")), raw.optString("owner_id"), raw.optInt("members"), raw.optInt("admins"), members, raw.optBoolean("can_manage"), raw.optBoolean("comments_enabled"), raw.optString("description")) }
    private fun key(server: String?, login: String?, suffix: String): String = MessageDigest.getInstance("SHA-256").digest("${server.orEmpty()}\n${login.orEmpty()}\n$suffix".toByteArray(Charsets.UTF_8)).joinToString("") { "%02x".format(it) } + ".json"
    private fun cacheFile(context: Context?, name: String): File { val root = context?.filesDir ?: throw IllegalStateException("cache context is unavailable"); val directory = File(root, "chat-cache"); if (!directory.exists()) directory.mkdirs(); return File(directory, name) }
    private fun write(context: Context?, name: String, value: String) { val target = cacheFile(context, name); val temp = File(target.parentFile, "${target.name}.tmp"); FileOutputStream(temp).use { it.write(value.toByteArray(Charsets.UTF_8)); it.flush() }; if (!temp.renameTo(target)) { target.delete(); temp.renameTo(target) } }
    private fun read(context: Context?, name: String): String = FileInputStream(cacheFile(context, name)).use { input -> val output = ByteArrayOutputStream(); val buffer = ByteArray(4096); while (true) { val count = input.read(buffer); if (count < 0) break; output.write(buffer, 0, count) }; output.toString("UTF-8") }
}
