package ru.e6atb.chat

import android.content.Context
import android.os.Build
import org.json.JSONArray
import org.json.JSONObject
import java.io.*
import java.net.HttpURLConnection
import java.net.URL
import java.security.MessageDigest
import java.util.Locale

internal object GithubOtaUpdater {
    private const val API_BASE = "https://api.github.com/repos/"; private const val APK_MIME = "application/vnd.android.package-archive"; private const val CONNECT_TIMEOUT_MS = 15000; private const val READ_TIMEOUT_MS = 30000; private var applicationContext: Context? = null
    class Update { @JvmField var versionName = ""; @JvmField var versionCode = -1; @JvmField var apkName = ""; @JvmField var apkUrl = ""; @JvmField var apkMime = APK_MIME; @JvmField var apkSha256 = ""; @JvmField var apkSize = -1L }
    @JvmStatic @Throws(Exception::class) fun findLatest(repository: String?, packageName: String?, currentVersionName: String?, currentVersionCode: Int): Update? = findLatest(repository, packageName, currentVersionName, currentVersionCode, deviceArchitecture())
    @JvmStatic @Throws(Exception::class) fun findLatest(repository: String?, packageName: String?, currentVersionName: String?, currentVersionCode: Int, architecture: String?): Update? { val repo = repository.orEmpty().trim(); if (repo.isEmpty() || !repo.contains('/')) throw IOException("GitHub repository is not configured"); val release = fetchJson("$API_BASE$repo/releases/latest"); val assets = release.optJSONArray("assets"); val metadata = findMetadataAsset(assets)?.let { fetchJson(it.optString("browser_download_url")) }; val apkMetadata = findApkMetadata(metadata, architecture); if (metadata?.optJSONObject("apks") != null && apkMetadata == null) throw IOException("release metadata has no APK for $architecture"); val expectedName = apkMetadata?.optString("apkName")?.trim().orEmpty(); if (expectedName.isNotEmpty() && !matchesArchitecture(expectedName.lowercase(Locale.US), architecture)) throw IOException("release APK architecture mismatch: $expectedName"); val asset = findApkAsset(assets, expectedName, architecture) ?: throw IOException(if (expectedName.isEmpty()) "release APK asset not found" else "release APK asset not found: $expectedName"); val versionName = metadata?.optString("versionName")?.takeIf { it.isNotEmpty() } ?: stripVersionPrefix(release.optString("tag_name")).ifEmpty { release.optString("name") }; val versionCode = metadata?.optInt("versionCode", -1) ?: -1; metadata?.optString("packageName")?.takeIf { it.isNotEmpty() && it != packageName }?.let { throw IOException("release package mismatch: $it") }; if (!isNewer(versionName, versionCode, currentVersionName, currentVersionCode)) return null; return Update().apply { this.versionName = versionName; this.versionCode = versionCode; apkName = asset.optString("name", "update.apk"); apkUrl = asset.optString("browser_download_url"); apkSha256 = apkMetadata?.optString("apkSha256").orEmpty(); apkSize = apkMetadata?.optLong("apkSize", -1) ?: -1; validateAssetSize(apkSize, asset.optLong("size", -1)); if (apkUrl.isEmpty()) throw IOException("release APK URL not found") } }
    @JvmStatic @Throws(Exception::class) fun download(context: Context?, update: Update?): File { val value = context ?: throw IOException("context is not available"); initialize(value); val release = update ?: throw IOException("update URL is empty"); if (release.apkUrl.isEmpty()) throw IOException("update URL is empty"); val directory = value.getExternalFilesDir(null) ?: value.filesDir ?: throw IOException("download folder is not available"); if (!directory.isDirectory && !directory.mkdirs()) throw IOException("download folder cannot be created"); val target = File(directory, "ove-rs-update-${safeFilePart(release.versionName.ifEmpty { "latest" })}.apk"); val temporary = File("${target.path}.tmp"); if (temporary.isFile && !temporary.delete()) throw IOException("old update temp file cannot be removed"); if (Armv6OtaTls.isRequired()) { Armv6OtaTls.download(value, release.apkUrl, temporary.absolutePath, if (release.apkSize >= 0) release.apkSize else 256L * 1024 * 1024); verifyFile(temporary, release.apkSha256, release.apkSize) } else downloadToFile(release.apkUrl, temporary, release.apkSha256, release.apkSize); if (target.isFile && !target.delete()) throw IOException("old update file cannot be removed"); if (!temporary.renameTo(target)) throw IOException("update file cannot be saved"); return target }
    @JvmStatic fun findApkAsset(assets: JSONArray?, expectedName: String?, architecture: String?): JSONObject? { val expected = expectedName.orEmpty().trim(); for (index in 0 until (assets?.length() ?: 0)) { val asset = assets?.optJSONObject(index) ?: continue; val name = asset.optString("name"); if (expected.isNotEmpty() && name == expected) return asset; if (expected.isEmpty() && name.lowercase(Locale.US).endsWith(".apk") && !name.lowercase(Locale.US).contains("debug") && matchesArchitecture(name.lowercase(Locale.US), architecture)) return asset }; return null }
    @JvmStatic fun findApkMetadata(metadata: JSONObject?, architecture: String?): JSONObject? { metadata ?: return null; return metadata.optJSONObject("apks")?.optJSONObject(architecture.orEmpty()) ?: metadata.takeIf { matchesArchitecture(it.optString("apkName").lowercase(Locale.US), architecture) } }
    @JvmStatic fun selectArchitecture(abis: Array<String?>?): String { abis?.forEach { abi -> val value = abi?.trim()?.lowercase(Locale.US).orEmpty(); when { value.contains("arm64") || value.contains("aarch64") -> return "arm64"; value.contains("x86_64") || value.contains("x86-64") -> return "x86_64"; value.contains("armeabi-v7a") || value.contains("armv7") -> return "armv7"; value == "armeabi" || value.contains("armv6") -> return "armv6" } }; return "" }
    @JvmStatic @Throws(IOException::class) fun validateAssetSize(metadataSize: Long, assetSize: Long) { if (metadataSize >= 0 && assetSize >= 0 && metadataSize != assetSize) throw IOException("release APK size mismatch") }
    @JvmStatic fun initialize(context: Context?) { applicationContext = context?.applicationContext ?: context }
    @JvmStatic fun isNewer(versionName: String?, versionCode: Int, currentVersionName: String?, currentVersionCode: Int) = if (versionCode >= 0) versionCode > currentVersionCode else compareVersionNames(versionName, currentVersionName) > 0
    @JvmStatic fun compareVersionNames(left: String?, right: String?): Int { val a = stripVersionPrefix(left).split(Regex("[^0-9A-Za-z]+")); val b = stripVersionPrefix(right).split(Regex("[^0-9A-Za-z]+")); for (index in 0 until maxOf(a.size, b.size)) { val av = a.getOrElse(index) { "0" }.ifEmpty { "0" }; val bv = b.getOrElse(index) { "0" }.ifEmpty { "0" }; val compare = if (av.all(Char::isDigit) && bv.all(Char::isDigit)) compareNumeric(av, bv) else av.compareTo(bv, true); if (compare != 0) return compare }; return 0 }
    private fun deviceArchitecture(): String { val value = selectArchitecture(if (Build.VERSION.SDK_INT >= 21) Build.SUPPORTED_ABIS else arrayOf(Build.CPU_ABI, Build.CPU_ABI2)); if (value.isEmpty()) throw IOException("unsupported update architecture"); return value }
    private fun matchesArchitecture(name: String?, architecture: String?) = !architecture.isNullOrEmpty() && name.orEmpty().endsWith("-${architecture.lowercase(Locale.US)}.apk")
    private fun findMetadataAsset(assets: JSONArray?): JSONObject? { for (index in 0 until (assets?.length() ?: 0)) assets?.optJSONObject(index)?.takeIf { it.optString("name").lowercase(Locale.US).let { name -> name == "update.json" || name.endsWith("-update.json") } }?.let { return it }; return null }
    private fun fetchJson(url: String) = JSONObject(readUrl(url)); private fun readUrl(url: String): String { if (Armv6OtaTls.isRequired()) return Armv6OtaTls.get(applicationContext ?: throw IOException("OTA context is unavailable"), url).toString(Charsets.UTF_8); return open(url).let { connection -> try { val code = connection.responseCode; val input = BufferedInputStream(if (code >= 400) connection.errorStream else connection.inputStream); input.use { val text = readAll(it); if (code !in 200..299) throw IOException("GitHub HTTP $code"); text } } finally { connection.disconnect() } } }
    private fun downloadToFile(url: String, target: File, checksum: String?, expectedSize: Long) { val connection = open(url); try { val code = connection.responseCode; if (code !in 200..299) throw IOException("download HTTP $code"); BufferedInputStream(connection.inputStream).use { input -> FileOutputStream(target).use { output -> val digest = checksum?.takeIf { it.isNotEmpty() }?.let { MessageDigest.getInstance("SHA-256") }; val buffer = ByteArray(64 * 1024); var total = 0L; while (true) { val count = input.read(buffer); if (count < 0) break; if (count > 0) { output.write(buffer, 0, count); total += count; digest?.update(buffer, 0, count) } }; if (expectedSize >= 0 && total != expectedSize) throw IOException("APK size mismatch"); if (digest != null && !hex(digest.digest()).equals(checksum, true)) throw IOException("APK checksum mismatch") } } } finally { connection.disconnect(); if (!target.isFile || target.length() == 0L) target.delete() } }
    private fun verifyFile(target: File, checksum: String?, expectedSize: Long) { if (!target.isFile) throw IOException("update file was not created"); if (expectedSize >= 0 && target.length() != expectedSize) { target.delete(); throw IOException("APK size mismatch") }; checksum?.takeIf { it.isNotEmpty() }?.let { expected -> val digest = MessageDigest.getInstance("SHA-256"); BufferedInputStream(FileInputStream(target)).use { input -> val buffer = ByteArray(64 * 1024); while (true) { val count = input.read(buffer); if (count < 0) break; if (count > 0) digest.update(buffer, 0, count) } }; if (!hex(digest.digest()).equals(expected, true)) { target.delete(); throw IOException("APK checksum mismatch") } } }
    private fun open(url: String): HttpURLConnection { if (url.isEmpty()) throw IOException("URL is empty"); return (URL(url).openConnection() as HttpURLConnection).apply { connectTimeout = CONNECT_TIMEOUT_MS; readTimeout = READ_TIMEOUT_MS; instanceFollowRedirects = true; setRequestProperty("Accept", "application/vnd.github+json, application/octet-stream"); setRequestProperty("User-Agent", "ove-rs-android/${BuildConfig.VERSION_NAME}") } }
    private fun readAll(input: InputStream): String = ByteArrayOutputStream().use { output -> val buffer = ByteArray(8192); while (true) { val count = input.read(buffer); if (count < 0) break; if (count > 0) output.write(buffer, 0, count) }; output.toString("UTF-8") }
    private fun compareNumeric(left: String, right: String): Int { val a = left.trimStart('0').ifEmpty { "0" }; val b = right.trimStart('0').ifEmpty { "0" }; return if (a.length != b.length) a.length.compareTo(b.length) else a.compareTo(b) }
    private fun stripVersionPrefix(value: String?) = value.orEmpty().trim().trimStart { it == 'v' || it == 'V' }; private fun safeFilePart(value: String) = value.map { if (it.isLetterOrDigit() || it == '.' || it == '_' || it == '-') it else '_' }.joinToString("").ifEmpty { "latest" }; private fun hex(bytes: ByteArray) = bytes.joinToString("") { "%02x".format(it) }
}
