package ru.e6atb.chat

import android.app.*
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.IBinder
import org.json.JSONObject
import kotlin.math.abs

class MessageSyncService : Service() {
    @Volatile private var running = false; private var worker: Thread? = null
    override fun onCreate() { super.onCreate(); AppLocale.apply(this); createChannels() }
    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int { if (intent?.action == ACTION_REJECT_CALL) { rejectCall(intent.getStringExtra(MainActivity.EXTRA_PEER)); return START_STICKY }; startForeground(FOREGROUND_ID, notification(SYNC_CHANNEL, getString(R.string.app_name), getString(R.string.sync_waiting), true)); if (!running) { running = true; worker = Thread(::pollLoop, "e6atb-sync").also { it.start() } }; return START_STICKY }
    override fun onDestroy() { running = false; worker?.interrupt(); super.onDestroy() }
    override fun onBind(intent: Intent?): IBinder? = null
    private fun pollLoop() { var failures = 0; while (running) { if (!SessionStore.hasSession(this)) { stopSelf(); return }; val server = SessionStore.server(this, MainActivity.DEFAULT_SERVER); val endpoint = SessionStore.transportEndpoint(this, MainActivity.DEFAULT_SERVER); val token = SessionStore.token(this); val userId = SessionStore.userId(this); val login = SessionStore.login(this); val api = MST5(this, endpoint, token, userId, login); try { try { CrashReportDispatcher.dispatch(this, api) } catch (_: Exception) { }; OutboxDispatcher.dispatch(this, api, null); val after = unifiedCursor(); startForeground(FOREGROUND_ID, notification(SYNC_CHANNEL, getString(R.string.app_name), if (login.isEmpty()) getString(R.string.status_online) else getString(R.string.status_online_as, login), true)); val updates = api.getUpdates(after, 30); val bootstrapped = SessionStore.notificationBootstrapComplete(this) || after > 0 || SessionStore.lastUpdate(this) > 0; val readIds = readMessageIds(updates); var newest = after
            updates.forEach { update -> newest = maxOf(newest, update.id); val message = update.message
                when {
                    (update.type == "message" || update.type == "channel_comment" || update.type == "message_edit" || update.type == "message_read" || update.type == "message_reaction") && message != null -> { val own = isOwnUser(message.from, userId, login); val otherUser = if (message.commentPostId > 0 || !message.to.roomKind.isNullOrEmpty()) message.to else if (own) message.to else message.from; val other = userAddress(otherUser); val peer = if (message.commentPostId > 0) OutboxStore.cachePeer(other, message.commentPostId) else other; ChatCache.appendMessage(this, server, login, peer, message); if (message.clientMessageId.isNotEmpty()) OutboxStore.complete(this, server, OutboxDispatcher.accountKey(this), message.clientMessageId); if (update.type == "message" && MessageNotificationPolicy.shouldNotify(bootstrapped, own, message.id, message.readAt, readIds)) { val code = oauthRequestCode(message); if (code.isNotEmpty()) showOAuthRequest(code, message) else showMessage(other, message.text) } else if (update.type == "message_read") cancelMessageNotification(other) }
                    update.type == "call_invite" && update.call?.from != null && !isOwnUser(update.call.from, userId, login) && !isStaleIncomingCall(update.call) -> showIncomingCall(userAddress(update.call.from))
                    update.type?.startsWith("call_") == true -> notificationManager()?.cancel(CALL_NOTIFICATION_ID)
                    update.type == "message_delete" && message != null -> { val other = if (message.commentPostId > 0) userAddress(message.to) else userAddress(if (isOwnUser(message.from, userId, login)) message.to else message.from); ChatCache.deleteMessage(this, server, login, if (message.commentPostId > 0) OutboxStore.cachePeer(other, message.commentPostId) else other, message.id) }
                    update.type == "chat_update" && update.room != null && !update.room.commentsEnabled -> { val channel = userAddress(update.room); ChatCache.deleteCommentThreads(this, server, login, channel); OutboxStore.removeChannelComments(this, server, OutboxDispatcher.accountKey(this), channel) }
                }
            }; SessionStore.backgroundLastUpdate(this, newest); SessionStore.lastUpdate(this, newest); if (newest > after) sendBroadcast(Intent(ACTION_SYNC_UPDATED).setPackage(packageName).putExtra("cursor", newest)); if (!SessionStore.notificationBootstrapComplete(this)) SessionStore.notificationBootstrapComplete(this, true); failures = 0
        } catch (error: Exception) { if (MST5.isInvalidTokenError(error)) { api.close(); SessionStore.clear(this); stopSelf(); return }; sleepWhileRunning(pollRetryDelayMs(failures++)) } finally { api.close() } } }
    private fun unifiedCursor(): Long { val foreground = SessionStore.lastUpdate(this); val background = SessionStore.backgroundLastUpdate(this); return if (foreground > 0 && background > 0) minOf(foreground, background) else maxOf(foreground, background) }
    private fun readMessageIds(updates: List<MST5.Update>?) = HashSet<Long>().also { result -> updates?.forEach { update -> update.message?.takeIf { update.type == "message_read" || it.readAt > 0 }?.let { result += it.id } } }
    private fun sleepWhileRunning(milliseconds: Long) { val end = System.currentTimeMillis() + milliseconds; while (running) { val remaining = end - System.currentTimeMillis(); if (remaining <= 0) return; try { Thread.sleep(minOf(remaining, 500)) } catch (_: InterruptedException) { Thread.currentThread().interrupt() } } }
    private fun rejectCall(peer: String?) { if (peer.isNullOrBlank() || !SessionStore.hasSession(this)) return; Thread({ var api: MST5? = null; try { api = MST5(this, SessionStore.transportEndpoint(this, MainActivity.DEFAULT_SERVER), SessionStore.token(this), SessionStore.userId(this), SessionStore.login(this)); api.sendCall(peer.trim(), "reject"); notificationManager()?.cancel(CALL_NOTIFICATION_ID) } catch (_: Exception) { } finally { api?.close() } }, "e6atb-call-reject").start() }
    private fun showMessage(from: String, text: String?) { val id = MESSAGE_BASE_ID + abs(from.hashCode()) % 100000; val pending = PendingIntent.getActivity(this, id, Intent(this, MainActivity::class.java).putExtra(MainActivity.EXTRA_CHAT, from), pendingIntentFlags()); notificationManager()?.notify(id, notification(MESSAGE_CHANNEL, from, text.orEmpty(), false).apply { contentIntent = pending }) }
    private fun cancelMessageNotification(from: String?) { if (!from.isNullOrEmpty()) notificationManager()?.cancel(MESSAGE_BASE_ID + abs(from.hashCode()) % 100000) }
    private fun oauthRequestCode(message: MST5.Message): String = try { JSONObject(message.data).takeIf { it.optString("kind") == "oauth_request" }?.let { OAuthCodeParser.parse(it.optString("user_code")) }.orEmpty() } catch (_: Exception) { "" }
    private fun showOAuthRequest(code: String, message: MST5.Message) { val service = try { JSONObject(message.data).optString("client_name", "Crypto Gateway") } catch (_: Exception) { "Crypto Gateway" }; val id = MESSAGE_BASE_ID + 900000 + abs(code.hashCode()) % 90000; val pending = PendingIntent.getActivity(this, id, Intent(Intent.ACTION_VIEW, Uri.parse("ovechat://authorize?user_code=$code"), this, MainActivity::class.java).setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP), pendingIntentFlags()); notificationManager()?.notify(id, notification(AUTH_CHANNEL, getString(R.string.oauth_authorize_title), "$service · $code", false).apply { contentIntent = pending; defaults = Notification.DEFAULT_SOUND or Notification.DEFAULT_VIBRATE; priority = Notification.PRIORITY_HIGH }) }
    private fun showIncomingCall(from: String) { val open = PendingIntent.getActivity(this, 9, Intent(this, MainActivity::class.java).setAction(MainActivity.ACTION_OPEN_CALL).putExtra(MainActivity.EXTRA_PEER, from).putExtra(MainActivity.EXTRA_CALL, from).setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP), pendingIntentFlags()); val accept = PendingIntent.getActivity(this, 10, Intent(this, MainActivity::class.java).setAction(MainActivity.ACTION_ACCEPT_CALL).putExtra(MainActivity.EXTRA_PEER, from), pendingIntentFlags()); val reject = PendingIntent.getService(this, 11, Intent(this, MessageSyncService::class.java).setAction(ACTION_REJECT_CALL).putExtra(MainActivity.EXTRA_PEER, from), pendingIntentFlags()); val builder = if (Build.VERSION.SDK_INT >= 26) Notification.Builder(this, CALL_CHANNEL) else Notification.Builder(this); notificationManager()?.notify(CALL_NOTIFICATION_ID, builder.setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(getString(R.string.notification_incoming_call)).setContentText(from).setContentIntent(open).setOngoing(true).setFullScreenIntent(open, true).setPriority(Notification.PRIORITY_HIGH).addAction(android.R.drawable.ic_menu_call, getString(R.string.action_accept), accept).addAction(android.R.drawable.ic_menu_close_clear_cancel, getString(R.string.action_decline), reject).build()) }
    private fun notification(channel: String, title: String, text: String, ongoing: Boolean): Notification { val builder = if (Build.VERSION.SDK_INT >= 26) Notification.Builder(this, channel) else Notification.Builder(this); return builder.setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(title).setContentText(text).setContentIntent(PendingIntent.getActivity(this, 0, Intent(this, MainActivity::class.java).setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP), pendingIntentFlags())).setOngoing(ongoing).setAutoCancel(!ongoing).build() }
    private fun createChannels() { if (Build.VERSION.SDK_INT < 26) return; val manager = notificationManager() ?: return; manager.createNotificationChannel(NotificationChannel(SYNC_CHANNEL, getString(R.string.notification_channel_sync), NotificationManager.IMPORTANCE_LOW)); manager.createNotificationChannel(NotificationChannel(MESSAGE_CHANNEL, getString(R.string.notification_channel_messages), NotificationManager.IMPORTANCE_DEFAULT)); manager.createNotificationChannel(NotificationChannel(AUTH_CHANNEL, getString(R.string.settings_authorization), NotificationManager.IMPORTANCE_HIGH)); manager.createNotificationChannel(NotificationChannel(CALL_CHANNEL, getString(R.string.notification_channel_calls), NotificationManager.IMPORTANCE_HIGH).apply { setSound(null, null); enableVibration(false); vibrationPattern = LongArray(0) }) }
    private fun pendingIntentFlags(): Int = PendingIntent.FLAG_UPDATE_CURRENT or if (Build.VERSION.SDK_INT >= 23) PendingIntent.FLAG_IMMUTABLE else 0
    private fun notificationManager() = getSystemService(NOTIFICATION_SERVICE) as? NotificationManager
    private fun isStaleIncomingCall(call: MST5.Call?) = call != null && call.date > 0 && System.currentTimeMillis() / 1000 - call.date > MAX_INCOMING_CALL_AGE_SEC
    companion object { const val ACTION_SYNC_UPDATED = "ru.e6atb.chat.SYNC_UPDATED"; private const val ACTION_REJECT_CALL = "ru.e6atb.chat.REJECT_CALL"; private const val SYNC_CHANNEL = "sync"; private const val MESSAGE_CHANNEL = "messages"; private const val CALL_CHANNEL = "calls_visual"; private const val AUTH_CHANNEL = "authorization"; private const val MAX_INCOMING_CALL_AGE_SEC = 120; private const val FOREGROUND_ID = 1; const val MESSAGE_BASE_ID = 1000; const val CALL_NOTIFICATION_ID = 2; @JvmStatic private fun isOwnUser(user: MST5.User?, userId: String?, login: String?) = user != null && if (!userId.isNullOrEmpty()) userId == user.id else !login.isNullOrEmpty() && login == user.login; @JvmStatic private fun userAddress(user: MST5.User?) = user?.login?.takeIf { it.isNotEmpty() } ?: user?.id.orEmpty(); @JvmStatic private fun pollRetryDelayMs(failures: Int) = minOf(5000L shl minOf(failures, 4), 60000L) }
}
