package ru.e6atb.chat

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import android.net.Uri
import android.os.Build
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileInputStream
import java.security.MessageDigest
import java.util.UUID

internal object OutboxStore {
    @JvmField val PREPARING = "preparing"; @JvmField val QUEUED = "queued"; @JvmField val SENDING = "sending"; @JvmField val FAILED = "failed"; @JvmField val CANCEL_REQUESTED = "cancel_requested"; const val MAX_TOTAL_BYTES = 128L * 1024L * 1024L
    private var helper: Helper? = null
    class Attachment { @JvmField var clientId = ""; @JvmField var fileId = ""; @JvmField var name = ""; @JvmField var mime = ""; @JvmField var localPath = ""; @JvmField var sourceUri = ""; @JvmField var size = 0L; @JvmField var photo = false; fun fileInfo() = MST5.FileInfo(fileId, name, mime, size) }
    class Entry { @JvmField var account = ""; @JvmField var id = ""; @JvmField var peer = ""; @JvmField var room = false; @JvmField var kind = ""; @JvmField var text = ""; @JvmField var name = ""; @JvmField var mime = ""; @JvmField var localPath = ""; @JvmField var sourceUri = ""; @JvmField var size = 0L; @JvmField var createdAt = 0L; @JvmField var state = ""; @JvmField var attempts = 0; @JvmField var retryAt = 0L; @JvmField var error = ""; @JvmField var commentPostId = 0L; @JvmField var replyToMessageId = 0L; @JvmField var maxDsrAmount = 0L; @JvmField var attachments = ArrayList<Attachment>(); @JvmField var progressPercent = 0; @JvmField var progressPhase = ""
        fun localMessage(me: MST5.User?, knownPeer: MST5.User?): MST5.Message { val target = knownPeer ?: if (room) MST5.User(peer, "", peer, peer, false, false, 0, "everyone", "everyone", "everyone", "group", "", 0, 0, null) else MST5.User("", "", peer, peer, false, false, 0); val media = ArrayList<MST5.FileInfo>().also { list -> attachments.forEach { list += it.fileInfo() }; if (list.isEmpty() && kind == "file") list += MST5.FileInfo("", name, mime, size) }; var preview = localPath.ifEmpty { sourceUri }; if (preview.isEmpty()) for (attachment in attachments) { val candidate = attachment.localPath.ifEmpty { attachment.sourceUri }; if (candidate.isNotEmpty()) { preview = candidate; break } }; return MST5.Message(-maxOf(1L, kotlin.math.abs(id.hashCode().toLong())), if (room) "chat:$peer" else "", me ?: MST5.User("", "", "", "", false, false, 0), target, text, createdAt, 0, media, null, false, false, "", id, 0, state, preview, ArrayList(), null, 0, commentPostId, 0, replyToMessageId, progressPercent, progressPhase) }
    }
    @JvmStatic @Synchronized @Throws(Exception::class) fun enqueueText(context: Context?, server: String?, user: String?, peer: String?, room: Boolean, text: String?): Entry = enqueueText(context, server, user, peer, room, text, 0)
    @JvmStatic @Synchronized @Throws(Exception::class) fun enqueueText(context: Context?, server: String?, user: String?, peer: String?, room: Boolean, text: String?, replyToMessageId: Long): Entry = base(peer, room).also { it.kind = "text"; it.text = text.orEmpty(); it.replyToMessageId = replyToMessageId.coerceAtLeast(0); insert(context, server, user, it) }
    @JvmStatic @Synchronized @Throws(Exception::class) fun enqueueComment(context: Context?, server: String?, user: String?, peer: String?, postId: Long, text: String?): Entry = enqueueComment(context, server, user, peer, postId, text, 0)
    @JvmStatic @Synchronized @Throws(Exception::class) fun enqueueComment(context: Context?, server: String?, user: String?, peer: String?, postId: Long, text: String?, replyToMessageId: Long): Entry = base(peer, true).also { it.kind = "text"; it.text = text.orEmpty(); it.commentPostId = postId; it.replyToMessageId = replyToMessageId.coerceAtLeast(0); insert(context, server, user, it) }
    @JvmStatic fun cachePeer(peer: String?, postId: Long): String = if (postId > 0) "comments:${peer.orEmpty()}:$postId" else peer.orEmpty()
    @JvmStatic @Synchronized @Throws(Exception::class) fun enqueueMedia(context: Context?, server: String?, user: String?, peer: String?, room: Boolean, text: String?, attachments: List<Attachment>?, clientMessageId: String?, maxDsrAmount: Long, commentPostId: Long, replyToMessageId: Long): Entry { val entry = base(peer, room); entry.id = clientMessageId.orEmpty(); entry.kind = "media"; entry.text = text.orEmpty(); entry.maxDsrAmount = maxDsrAmount.coerceAtLeast(0); entry.commentPostId = commentPostId.coerceAtLeast(0); entry.replyToMessageId = replyToMessageId.coerceAtLeast(0); attachments?.let { entry.attachments.addAll(it) }; val total = entry.attachments.sumOf { it.size.coerceAtLeast(0) } + load(context, server, user).sumOf { it.size.coerceAtLeast(0) }; if (total > MAX_TOTAL_BYTES) throw IllegalStateException("outbox is full (128 MiB)"); entry.size = entry.attachments.sumOf { it.size.coerceAtLeast(0) }; insert(context, server, user, entry); return entry }
    @JvmStatic @Synchronized fun load(context: Context?, server: String?, user: String?): List<Entry> {
        val account = account(server, user)
        migrateLegacy(context, server, user, account)
        val database = db(context)
        return ArrayList<Entry>().also { out ->
            database.query("outbox", null, "account=?", arrayOf(account), null, null, "created_at,id").use { cursor ->
                while (cursor.moveToNext()) fromCursor(cursor).also { entry ->
                    loadAttachments(database, entry)
                    out += entry
                }
            }
        }
    }
    @JvmStatic @Synchronized fun peersReady(context: Context?, server: String?, user: String?, now: Long): List<String> { val seen = HashSet<String>(); return load(context, server, user).filter { it.state != FAILED && it.state != CANCEL_REQUESTED && it.retryAt <= now && seen.add(it.peer) }.map { it.peer } }
    @JvmStatic @Synchronized fun claimNext(context: Context?, server: String?, user: String?, peer: String?, now: Long): Entry? { for (entry in load(context, server, user)) { if (entry.peer != peer) continue; if (entry.state == FAILED || entry.state == CANCEL_REQUESTED || entry.retryAt > now) return null; entry.state = SENDING; update(context, server, user, entry); return entry }; return null }
    @JvmStatic @Synchronized fun update(context: Context?, server: String?, user: String?, changed: Entry) { changed.account = account(server, user); db(context).update("outbox", values(changed), "account=? AND id=?", arrayOf(changed.account, changed.id)) }
    @JvmStatic @Synchronized fun find(context: Context?, server: String?, user: String?, id: String?): Entry? = load(context, server, user).firstOrNull { it.id == id }
    @JvmStatic @Synchronized fun requestCancel(context: Context?, server: String?, user: String?, id: String?): Boolean = find(context, server, user, id)?.let { it.state = CANCEL_REQUESTED; it.retryAt = 0; update(context, server, user, it); true } ?: false
    @JvmStatic @Synchronized fun complete(context: Context?, server: String?, user: String?, id: String?) { find(context, server, user, id)?.let { entry -> deletePayload(entry); if (Build.VERSION.SDK_INT >= 19) entry.attachments.map { it.sourceUri }.plus(entry.sourceUri).filter { it.isNotEmpty() }.forEach { uri -> try { context?.contentResolver?.releasePersistableUriPermission(Uri.parse(uri), Intent.FLAG_GRANT_READ_URI_PERMISSION) } catch (_: Exception) { } } }; val account = account(server, user); db(context).delete("outbox_media", "account=? AND message_id=?", arrayOf(account, id)); db(context).delete("outbox", "account=? AND id=?", arrayOf(account, id)) }
    @JvmStatic @Synchronized fun retry(context: Context?, server: String?, user: String?, id: String?) { find(context, server, user, id)?.let { it.state = QUEUED; it.retryAt = 0; it.error = ""; update(context, server, user, it) } }
    @JvmStatic @Synchronized fun count(context: Context?, server: String?, user: String?) = load(context, server, user).size
    @JvmStatic @Synchronized fun clear(context: Context?, server: String?, user: String?) { load(context, server, user).forEach(::deletePayload); val account = account(server, user); db(context).delete("outbox_media", "account=?", arrayOf(account)); db(context).delete("outbox", "account=?", arrayOf(account)) }
    @JvmStatic @Synchronized fun removeChannelComments(context: Context?, server: String?, user: String?, peer: String?) { load(context, server, user).filter { it.commentPostId > 0 && it.peer == peer }.forEach { complete(context, server, user, it.id) } }
    @JvmStatic fun payloadFile(context: Context?, id: String?): File { val directory = File(context?.filesDir ?: throw IllegalArgumentException("context is required"), "outbox-payloads"); if (!directory.exists()) directory.mkdirs(); return File(directory, "${id.orEmpty()}.bin") }
    private fun base(peer: String?, room: Boolean) = Entry().apply { id = UUID.randomUUID().toString(); this.peer = peer.orEmpty(); this.room = room; createdAt = System.currentTimeMillis() / 1000; state = QUEUED }
    private fun insert(context: Context?, server: String?, user: String?, entry: Entry) { entry.account = account(server, user); migrateLegacy(context, server, user, entry.account); db(context).beginTransaction(); try { db(context).insertOrThrow("outbox", null, values(entry)); insertAttachments(db(context), entry); db(context).setTransactionSuccessful() } finally { db(context).endTransaction() } }
    private fun insertAttachments(database: SQLiteDatabase, entry: Entry) { entry.attachments.forEachIndexed { position, attachment -> database.insertOrThrow("outbox_media", null, ContentValues().apply { put("account", entry.account); put("message_id", entry.id); put("position", position); put("client_id", attachment.clientId); put("file_id", attachment.fileId); put("name", attachment.name); put("mime", attachment.mime); put("local_path", attachment.localPath); put("source_uri", attachment.sourceUri); put("size", attachment.size); put("photo", if (attachment.photo) 1 else 0) }) } }
    private fun loadAttachments(database: SQLiteDatabase, entry: Entry) { database.query("outbox_media", null, "account=? AND message_id=?", arrayOf(entry.account, entry.id), null, null, "position").use { cursor -> while (cursor.moveToNext()) entry.attachments += Attachment().apply { clientId = text(cursor, "client_id"); fileId = text(cursor, "file_id"); name = text(cursor, "name"); mime = text(cursor, "mime"); localPath = text(cursor, "local_path"); sourceUri = text(cursor, "source_uri"); size = number(cursor, "size"); photo = number(cursor, "photo") != 0L } } }
    private fun values(entry: Entry) = ContentValues().apply { put("account", entry.account); put("id", entry.id); put("peer", entry.peer); put("room", if (entry.room) 1 else 0); put("kind", entry.kind); put("text", entry.text); put("name", entry.name); put("mime", entry.mime); put("local_path", entry.localPath); put("source_uri", entry.sourceUri); put("size", entry.size); put("created_at", entry.createdAt); put("state", entry.state); put("attempts", entry.attempts); put("retry_at", entry.retryAt); put("error", entry.error); /* Kept for the v3 on-device schema; no longer read by Kotlin. */ put("prepared_body", ""); put("comment_post_id", entry.commentPostId); put("reply_to_message_id", entry.replyToMessageId); put("media_reservation_id", ""); put("max_dsr_amount", entry.maxDsrAmount) }
    private fun fromCursor(cursor: Cursor) = Entry().apply { account = text(cursor, "account"); id = text(cursor, "id"); peer = text(cursor, "peer"); room = number(cursor, "room") != 0L; kind = text(cursor, "kind"); text = text(cursor, "text"); name = text(cursor, "name"); mime = text(cursor, "mime"); localPath = text(cursor, "local_path"); sourceUri = text(cursor, "source_uri"); size = number(cursor, "size"); createdAt = number(cursor, "created_at"); state = text(cursor, "state"); attempts = number(cursor, "attempts").toInt(); retryAt = number(cursor, "retry_at"); error = text(cursor, "error"); commentPostId = number(cursor, "comment_post_id"); replyToMessageId = number(cursor, "reply_to_message_id"); maxDsrAmount = number(cursor, "max_dsr_amount") }
    private fun text(cursor: Cursor, column: String) = cursor.getString(cursor.getColumnIndexOrThrow(column)) ?: ""; private fun number(cursor: Cursor, column: String) = cursor.getLong(cursor.getColumnIndexOrThrow(column))
    private fun db(context: Context?): SQLiteDatabase { if (helper == null) helper = Helper(context?.applicationContext ?: throw IllegalArgumentException("context is required")); return helper!!.writableDatabase }
    private fun account(server: String?, user: String?) = digest("${server.orEmpty()}\n${user.orEmpty()}"); private fun digest(value: String) = MessageDigest.getInstance("SHA-256").digest(value.toByteArray(Charsets.UTF_8)).joinToString("") { "%02x".format(it) }
    private fun migrateLegacy(context: Context?, server: String?, user: String?, account: String) { val legacy = File(File(context?.filesDir ?: return, "outbox"), "$account.json"); if (!legacy.isFile) return; val database = db(context); database.beginTransaction(); try { val array = JSONArray(read(legacy)); for (index in 0 until array.length()) array.optJSONObject(index)?.let { raw -> val entry = fromJson(raw).apply { this.account = account }; database.insertWithOnConflict("outbox", null, values(entry), SQLiteDatabase.CONFLICT_IGNORE); if (entry.kind == "file" && entry.size > 0) { entry.attachments += Attachment().apply { clientId = "attachment-000001"; name = entry.name; mime = entry.mime; localPath = entry.localPath; sourceUri = entry.sourceUri; size = entry.size }; insertAttachments(database, entry) } }; database.setTransactionSuccessful() } catch (_: Exception) { } finally { database.endTransaction() }; legacy.delete() }
    private fun fromJson(raw: JSONObject) = Entry().apply { id = raw.optString("id"); peer = raw.optString("peer"); room = raw.optBoolean("room"); kind = raw.optString("kind"); text = raw.optString("text"); name = raw.optString("name"); mime = raw.optString("mime"); localPath = raw.optString("local_path"); size = raw.optLong("size"); createdAt = raw.optLong("created_at"); state = raw.optString("state", QUEUED).let { if (it == SENDING) QUEUED else it }; attempts = raw.optInt("attempts"); retryAt = raw.optLong("retry_at"); error = raw.optString("error"); commentPostId = raw.optLong("comment_post_id"); replyToMessageId = raw.optLong("reply_to_message_id"); maxDsrAmount = raw.optLong("max_dsr_amount") }
    private fun deletePayload(entry: Entry) { listOf(entry.localPath).plus(entry.attachments.map { it.localPath }).filter { it.isNotEmpty() }.forEach { try { File(it).delete() } catch (_: Exception) { } } }
    private fun read(file: File) = FileInputStream(file).use { input -> val output = ByteArrayOutputStream(); val buffer = ByteArray(4096); while (true) { val count = input.read(buffer); if (count < 0) break; output.write(buffer, 0, count) }; output.toString("UTF-8") }
    private class Helper(context: Context) : SQLiteOpenHelper(context, "outbox-v2.db", null, 3) { override fun onCreate(db: SQLiteDatabase) { db.execSQL("CREATE TABLE outbox (account TEXT NOT NULL,id TEXT NOT NULL,peer TEXT NOT NULL,room INTEGER NOT NULL,kind TEXT NOT NULL,text TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,local_path TEXT NOT NULL,source_uri TEXT NOT NULL,size INTEGER NOT NULL,created_at INTEGER NOT NULL,state TEXT NOT NULL,attempts INTEGER NOT NULL,retry_at INTEGER NOT NULL,error TEXT NOT NULL,prepared_body TEXT NOT NULL,comment_post_id INTEGER NOT NULL,reply_to_message_id INTEGER NOT NULL,media_reservation_id TEXT NOT NULL,max_dsr_amount INTEGER NOT NULL,PRIMARY KEY(account,id))"); db.execSQL("CREATE INDEX outbox_ready ON outbox(account,peer,state,retry_at,created_at)"); db.execSQL("CREATE TABLE outbox_media (account TEXT NOT NULL,message_id TEXT NOT NULL,position INTEGER NOT NULL,client_id TEXT NOT NULL,file_id TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,local_path TEXT NOT NULL,source_uri TEXT NOT NULL,size INTEGER NOT NULL,photo INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(account,message_id,position))"); db.execSQL("CREATE INDEX outbox_media_message ON outbox_media(account,message_id,position)") }; override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) { if (oldVersion < 2) { db.execSQL("CREATE TABLE IF NOT EXISTS outbox_media (account TEXT NOT NULL,message_id TEXT NOT NULL,position INTEGER NOT NULL,client_id TEXT NOT NULL,file_id TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,local_path TEXT NOT NULL,source_uri TEXT NOT NULL,size INTEGER NOT NULL,PRIMARY KEY(account,message_id,position))"); db.execSQL("CREATE INDEX IF NOT EXISTS outbox_media_message ON outbox_media(account,message_id,position)"); db.execSQL("INSERT OR IGNORE INTO outbox_media(account,message_id,position,client_id,file_id,name,mime,local_path,source_uri,size) SELECT account,id,0,'attachment-000001','',name,mime,local_path,source_uri,size FROM outbox WHERE kind='file' AND size>0"); db.execSQL("UPDATE outbox SET kind='media',text='' WHERE kind='file'") }; if (oldVersion < 3) db.execSQL("ALTER TABLE outbox_media ADD COLUMN photo INTEGER NOT NULL DEFAULT 0") }; override fun onOpen(db: SQLiteDatabase) { super.onOpen(db); db.update("outbox", ContentValues().apply { put("state", QUEUED) }, "state=? OR state=?", arrayOf(SENDING, PREPARING)) } }
}
